### ISSUE TITLE
NoSuchMethodError: CompilerOptions.versionToJdkLevel with Android Gradle Plugin 2.3.0-alpha1

### ISSUE THREAD

**Issue by Quarx2k** [greenrobot/greenDAO#498]
Hello. I have a problem with migration to greendao3. 
I follow guide http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/

New classes generated successfully. Gradle greendao plugin added and applied. But while compiling, i get error:

```
Caused by: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.impl.CompilerOptions.versionToJdkLevel(Ljava/lang/Object;)J
        at org.eclipse.jdt.core.dom.ASTConverter.<init>(ASTConverter.java:91)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.convert(CompilationUnitResolver.java:285)
        at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1216)
        at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:812)
        at org.greenrobot.greendao.codemodifier.EntityClassParser.parse(EntityClassParser.kt:25)
```

I tried clean project, remove .gradle dir, nothing helps.
Full stacktrace: http://pastebin.com/shPg8Wi7

Android studio 2.3. 
Gradle: com.android.tools.build:gradle:2.3.0-alpha1.
Greendao 3.2.0.

What can be wrong? Thanks :)

**Comment by thunde91** [comment]
Same issue with me, using gradle 2.2.2 is fine, upgrade to 2.3.0-aplha1 have this issue.

**Comment by Quarx2k** [comment]
Yes, with 2.2.2 is ok. Downgraded for now

**Comment by greenrobot-team** [comment]
Will keep this open for reference if this still is broken once the final 2.3.0 version of the Android Gradle Plugin is released. alpha is rather early and things are expected to be broken. -ut

**Comment by Quarx2k** [comment]
Just for notify:  gradle:2.3.0-alpha2 + greendao3.2.1, same problem.

**Comment by thunde91** [comment]
the same also happen gradle:2.3.0-aplha3

**Comment by NeoSyder** [comment]
It seem to works with gradle:2.3.0-beta2. My app did not crash when creating the DB :)

**Comment by greenrobot** [comment]
@NeoSyder Does that include Gradle 3.3 in your set up?

**Comment by NeoSyder** [comment]
Yep exactly, I use Gradle 3.3

**Comment by caarmen** [comment]
I'm having this problem with:
* gradle 3.3
* `classpath 'com.android.tools.build:gradle:2.3.0-beta2'`
* `classpath 'org.greenrobot:greendao-gradle-plugin:3.2.1'`
* `compile 'org.greenrobot:greendao:3.2.0'`

**Comment by greenrobot-team** [comment]
Testing this now. Will update with results.

**Working configurations**
- Android Studio 2.2.3 (current stable release), Android Plugin 2.2.3 (current stable), Gradle 3.3 (current stable)

**Broken configuations**
- ...

-ut

**Comment by greenrobot-team** [comment]
@caarmen I saw you already removed it: but make sure to move the `buildscript` block to the very top of your file. Also, try to include the greenDAO plugin in the root `buildscript` block at the same level as the Android plugin. -ut

**Comment by thunde91** [comment]
tested on 2.3 beta 3 , still same issue

**Comment by caarmen** [comment]
Sorry for the delay!

Moving the greendao plugin classpath to the root build.gradle file fixed this issue! Thanks :) 

I didn't have to change the position of the buildscript block in my app/build.gradle file.

**Comment by ximencx** [comment]
解决方法就是：buildscript 放到application下

**Comment by wodis** [comment]
I have fixed this issue. I put this `classpath 'org.greenrobot:greendao-gradle-plugin:3.2.1'` in the application's **buildscript** not the top. Then making this classpath to the top and resolved it.

**Comment by Cataalinn** [comment]
`classpath 'org.greenrobot:greendao-gradle-plugin:3.2.1'` with stable Android studio 2.3 is not working. Same error.

**Comment by svladim** [comment]
Move  "lasspath 'org.greenrobot:greendao-gradle-plugin:3.2.1'"  to the root build.gradle file. I have it worked with Android Studio 2.3.

**Comment by smarques84** [comment]
I also confirm i fixed the issue in Android Studio 2.3 by moving the `classpath 'org.greenrobot:greendao-gradle-plugin:3.2.1'` from app.gradle file to project build.gradle file

**Comment by PattaFeuFeu** [comment]
It does work when moving the `classpath` to the root build.gradle file. However, I have a multi-project setup where not all of the subprojects actually use greenDAO. Is there currently an option to get the build working without moving the classpath?

**Comment by smarques84** [comment]
@PattaFeuFeu not sure we will have to wait for @greenrobot-team to provide a fix

**Comment by greenrobot-team** [comment]
@PattaFeuFeu The plugin is only applied to the projects where you add the `apply plugin: 'org.greenrobot.greendao'` statement. It is a good idea anyhow to have only one buildscript block in your root `build.gradle` file. -ut

**Comment by greenrobot** [comment]
We just published 3.2.2 - can someone please confirm that it is working now without any workarounds? Thanks!

**Comment by lazytes** [comment]
The newest version worked when add greeddao-gradle-plugin in module's build.gradle

**Comment by greenrobot** [comment]
@lazytes Thanks!

**Comment by pirhano** [comment]
The solution is to move

classpath 'org.greenrobot:greendao-gradle-plugin:3.2.0'

form app/build.gradle into top level build.gradle file.

Example:
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.0'
    }
}

it work for me with gradle 3.3 and SDK android 2.3.1
copied from https://stackoverflow.com/questions/42610364/build-fails-for-greendao-3-2-with-compileroptions-versiontojdklevel/42610365#42610365
