### ISSUE TITLE
NoClassDefFoundError on DaoObject

### ISSUE THREAD

**Issue by leberrm** [greenrobot/greenDAO#266]
I'm working on an Android app that has been created initially by someone else. This app is using GreenDao 2.0.0 to store objects from the API. Everything works fine on some devices (like Nexus 5) but for some reasons, it's not working on my Android 4.2 and 4.4 devices. The code compiles but when I want to launch my app it crashes and I get the following error :

11-04 16:26:35.951 6614-6614/com.myeggbox E/AndroidRuntime: FATAL EXCEPTION: main 11-04 16:26:35.951 6614-6614/com.myeggbox E/AndroidRuntime: Process: com.myeggbox, PID: 6614 **11-04 16:26:35.951 6614-6614/com.myeggbox E/AndroidRuntime: java.lang.NoClassDefFoundError: com.myeggbox.api.data.entity.AddressDao

I never used GreenDao before so I'm lost, if someone has any idea ... In my build.gradle the targetSdk is 22 and the minSdkVersion is 16. This is my EntityGenerator.java:

package com.entityGenerator;

import de.greenrobot.daogenerator.DaoGenerator;
import de.greenrobot.daogenerator.Entity;
import de.greenrobot.daogenerator.Property;
import de.greenrobot.daogenerator.Schema;

public class EntityGenerator {
    private static Entity product;
    private static Entity egg;
    private static Entity category;
    private static Entity store;
    private static Entity document;
    private static Entity code;
    private static Entity brand;
    private static Entity service;
    private static Entity address;
    private static Entity review;
    private static Entity user;

```
public static void main(String[] args) throws Exception {
    Schema schema = new Schema(4, "com.tymate.myeggbox.api.data.entity");
    schema.enableKeepSectionsByDefault();

    createEntities(schema);
    mapEntities();
    addRelationShip();

    new DaoGenerator().generateAll(schema, "../app/src/main/java/");
}

private static void createEntities(final Schema schema) {
    address = schema.addEntity("Address");
    brand = schema.addEntity("Brand");
    category = schema.addEntity("Category");
    code = schema.addEntity("Code");
    document = schema.addEntity("Document");
    egg = schema.addEntity("Egg");
    product = schema.addEntity("Product");
    review = schema.addEntity("Review");
    service = schema.addEntity("Service");
    user = schema.addEntity("User");
    store = schema.addEntity("Store");
}

private static void mapEntities() {
    addEgg();
    addCategory();
    addCode();
    addDocument();
    addProduct();
    addStore();
    addBrand();
    addService();
    addAddress();
    addReview();
    addUser();
}

private static void addRelationShip() {
    //egg <-> user
    Property egg_user_id = egg.addLongProperty("user_id").getProperty();
    egg.addToOne(user, egg_user_id).setName("userDb");//liaison vers l'utilisateur
    user.addToMany(egg, egg_user_id).setName("eggListDb");//liaison inverse

    //egg <-> product
    Property egg_product_id = egg.addLongProperty("product_id").getProperty();
    egg.addToOne(product, egg_product_id).setName("productDb");//liaison vers le product
    product.addToMany(egg, egg_product_id).setName("eggListDb");//liaison inverse

    //code <-> egg
    Property code_egg_id = code.addLongProperty("egg_id_db").getProperty();
    code.addToOne(egg, code_egg_id).setName("eggDb");//liaison du code vers l'egg
    egg.addToMany(code, code_egg_id).setName("codeListDb");//liaison inverse

    //code <-> user
    Property code_user_id = code.addLongProperty("user_id").getProperty();
    code.addToOne(user, code_user_id).setName("userDb");
    user.addToMany(code, code_user_id).setName("codeListDb");

    //documents <-> egg
    Property doc_egg_id = document.addLongProperty("egg_id").getProperty();
    document.addToOne(egg, doc_egg_id).setName("eggDb");//liaison vers l'egg
    egg.addToMany(document, doc_egg_id).setName("documentListDb");//liaison inverse

    //egg <-> store
    Property egg_store_id = egg.addLongProperty("store_id").getProperty();
    egg.addToOne(store, egg_store_id).setName("storeDb");//relation vers l'egg
    store.addToMany(egg, egg_store_id).setName("eggListDb");//relation inverse

    //product <-> brand
    Property product_brand_id = product.addLongProperty("brand_id").getProperty();
    product.addToOne(brand, product_brand_id).setName("brandDb");//liaison vers le product
    brand.addToMany(product, product_brand_id).setName("productListDb");//liaison inverse

    //product <-> category
    Property product_category_id = product.addLongProperty("category_id").getProperty();
    product.addToOne(category, product_category_id).setName("categoryDb");//liaison vers la category
    category.addToMany(product, product_category_id).setName("productListDb");//liaison inverse

    //service <-> egg
    Property service_egg_id = service.addLongProperty("egg_local_id").getProperty();
    service.addToOne(egg, service_egg_id);//relation vers l'egg
    egg.addToMany(service, service_egg_id).setName("serviceListDb");//relation inverse

    //review <-> product
    Property review_product_id = review.addLongProperty("product_id").getProperty();
    review.addToOne(product, review_product_id).setName("productDB");//liaison vers le product
    product.addToMany(review, review_product_id).setName("reviewListDb");//liaison inverse

    //address <-> user
    Property address_user_id = address.addLongProperty("user_id").getProperty();
    address.addToOne(user, address_user_id).setName("userDB");//liaison vers le user
    user.addToMany(address, address_user_id).setName("addressListDb");//liaison inverse
}

private static void addEgg() {
    egg.implementsInterface("Serializable", "Comparable<Egg>");
    egg.addLongProperty("localId").primaryKey().autoincrement();
    egg.addStringProperty("buying_date");
    egg.addLongProperty("id");
    egg.addStringProperty("picture");
    egg.addIntProperty("warranty_duration");
    egg.addStringProperty("created_at");
    egg.addStringProperty("localPicture");
}

private static void addCode() {
    code.implementsInterface("Serializable");
    code.addLongProperty("localId").primaryKey().autoincrement();
    code.addLongProperty("id");
    code.addStringProperty("digest");
}

private static void addDocument() {
    document.implementsInterface("Serializable");
    document.addLongProperty("localId").primaryKey().autoincrement();
    document.addStringProperty("content");
    document.addStringProperty("created_at");
    document.addLongProperty("id");
    document.addStringProperty("picture");
    document.addStringProperty("preview");
    document.addStringProperty("title");
    document.addStringProperty("UUID");
    document.addStringProperty("updated_at");
    document.addStringProperty("localPath");
    document.addStringProperty("type");
}

private static void addStore() {
    store.implementsInterface("Serializable");
    store.addLongProperty("localId").primaryKey().autoincrement();
    store.addLongProperty("id");
    store.addStringProperty("name");
    store.addStringProperty("phone");
    store.addStringProperty("email");
    store.addStringProperty("website");
    store.addStringProperty("street_name");
    store.addStringProperty("city");
    store.addStringProperty("zip_code");
    store.addStringProperty("country");
    store.addStringProperty("facebook_url");
    store.addStringProperty("logo");
    store.addStringProperty("latitude");
    store.addStringProperty("longitude");
}

private static void addProduct() {
    product.implementsInterface("Serializable");
    product.addLongProperty("localId").primaryKey().autoincrement();
    product.addLongProperty("id");
    product.addStringProperty("name");
    product.addStringProperty("picture");
    product.addStringProperty("ean");
}

private static void addBrand() {
    brand.implementsInterface("Serializable");
    brand.addLongProperty("localId").primaryKey().autoincrement();
    brand.addLongProperty("id");
    brand.addStringProperty("name");
}

private static void addCategory() {
    category.implementsInterface("Serializable");
    category.addLongProperty("localId").primaryKey().autoincrement();
    category.addLongProperty("id");
    category.addStringProperty("image");
    category.addStringProperty("name");
}

private static void addService() {
    service.implementsInterface("Serializable");
    service.addLongProperty("localId").primaryKey().autoincrement();
    service.addLongProperty("id");
    service.addStringProperty("kind");
    service.addStringProperty("phone");
    service.addStringProperty("title");
    service.addStringProperty("web_url");
    service.addStringProperty("local_path");
}

private static void addUser() {
    user.implementsInterface("Serializable");
    user.addLongProperty("localId").primaryKey().autoincrement();
    user.addStringProperty("id");
    user.addStringProperty("email");
    user.addStringProperty("authentication_token");
}

private static void addAddress() {
    address.implementsInterface("Serializable");
    address.addLongProperty("localId").primaryKey().autoincrement();
    address.addStringProperty("city");
    address.addStringProperty("country");
    address.addStringProperty("firstname");
    address.addLongProperty("id");
    address.addStringProperty("lastname");
    address.addStringProperty("street_name");
    address.addStringProperty("zip_code");
}

private static void addReview() {
    review.implementsInterface("Serializable");
    review.addLongProperty("localId").primaryKey().autoincrement();
    review.addStringProperty("content");
    review.addStringProperty("created_at");
    review.addLongProperty("id");
    review.addStringProperty("locale");
    review.addIntProperty("rate");
    review.addStringProperty("title");
    review.addStringProperty("upload_at");
    review.addIntProperty("user_id");
}
```

}

Thanks for your help !

**Comment by greenrobot** [comment]
Not sure what to make of that. Could you post the full stack trace of the exception?

**Comment by leberrm** [comment]
Sure, this is the full stack trace when I run my app : 

12-01 08:25:51.420 995-995/com.tymate.myeggbox E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 java.lang.NoClassDefFoundError: com.tymate.myeggbox.api.data.entity.AddressDao
                                                                     at com.tymate.myeggbox.api.data.entity.DaoMaster.createAllTables(DaoMaster.java:32)
                                                                     at com.tymate.myeggbox.api.data.entity.DaoMaster$OpenHelper.onCreate(DaoMaster.java:69)
                                                                     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
                                                                     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                                                                     at com.tymate.myeggbox.MyEggBoxApp.initDb(MyEggBoxApp.java:62)
                                                                     at com.tymate.myeggbox.MyEggBoxApp.onCreate(MyEggBoxApp.java:56)
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:130)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:137)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                     at dalvik.system.NativeStart.main(Native Method)

So the error seems to be in DaoMaster.java, that's a file generated by the EntityGenerator, am I right ? This is why I posted my Generator, I thought I was doing something wrong there.

**Comment by ccaronls** [comment]
Here is a clue:
Schema schema = new Schema(4, "com.tymate.myeggbox.api.data.entity");

 java.lang.NoClassDefFoundError: com.myeggbox.api.data.entity.AddressDao

**Comment by gonzapico** [comment]
Any new?

**Comment by gonzapico** [comment]
In my case, it happens when DAO tries to create a table if it doesn't exist with the method:
ListaDBDao.createTable(db, ifNotExists);

public class ListaDBDao extends AbstractDao<ListDB, Long> {

public class ListaDB implements Parcelable {

I think the trouble it is becuase of the db class implements Parcelable. I say this because the method createAllTables(SQLiteDatabase db, boolean ifNotExists) starts like this..

 public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        TiendaDBDao.createTable(db, ifNotExists);
        LisatDBDao.createTable(db, ifNotExists);
.. and it doesn't crash on the first line (and TiendaDB doesn't implement Parcelable).

I hope this helps to you! ;)

**Comment by smarterxiao** [comment]
I have the same  problem .  @leberrm

**Comment by smarterxiao** [comment]
11-18 16:50:48.472 24279-24279/com.idongme.app.go I/dalvikvm: Could not find method com.idongme.greendaodemo.greendao.gen.DaoSession.getGameSaveEntityDao, referenced from method com.idongme.app.go.helper.SQLHelper.getGameSaveEntity
11-18 16:50:48.472 24279-24279/com.idongme.app.go W/dalvikvm: VFY: unable to resolve virtual method 37456: Lcom/idongme/greendaodemo/greendao/gen/DaoSession;.getGameSaveEntityDao ()Lcom/idongme/greendaodemo/greendao/gen/GameSaveEntityDao;
11-18 16:50:48.472 24279-24279/com.idongme.app.go I/dalvikvm: Could not find method com.idongme.greendaodemo.greendao.gen.DaoSession.getMyLatlngDao, referenced from method com.idongme.app.go.helper.SQLHelper.getMyLatLngDao
11-18 16:50:48.472 24279-24279/com.idongme.app.go W/dalvikvm: VFY: unable to resolve virtual method 37457: Lcom/idongme/greendaodemo/greendao/gen/DaoSession;.getMyLatlngDao ()Lcom/idongme/greendaodemo/greendao/gen/MyLatlngDao;
11-18 16:50:48.472 24279-24279/com.idongme.app.go I/dalvikvm: Could not find method com.idongme.greendaodemo.greendao.gen.DaoSession.getRunSetBeanDao, referenced from method com.idongme.app.go.helper.SQLHelper.getRunSetBean
11-18 16:50:48.472 24279-24279/com.idongme.app.go W/dalvikvm: VFY: unable to resolve virtual method 37458: Lcom/idongme/greendaodemo/greendao/gen/DaoSession;.getRunSetBeanDao ()Lcom/idongme/greendaodemo/greendao/gen/RunSetBeanDao;
11-18 16:50:48.472 24279-24279/com.idongme.app.go I/dalvikvm: Could not find method com.idongme.greendaodemo.greendao.gen.DaoSession.getRunStatusDao, referenced from method com.idongme.app.go.helper.SQLHelper.getRunStatus
11-18 16:50:48.472 24279-24279/com.idongme.app.go W/dalvikvm: VFY: unable to resolve virtual method 37459: Lcom/idongme/greendaodemo/greendao/gen/DaoSession;.getRunStatusDao ()Lcom/idongme/greendaodemo/greendao/gen/RunStatusDao;
11-18 16:50:48.472 24279-24279/com.idongme.app.go E/dalvikvm: Could not find class 'com.idongme.greendaodemo.greendao.gen.DaoMaster$DevOpenHelper', referenced from method com.idongme.app.go.helper.SQLHelper.init
11-18 16:50:48.472 24279-24279/com.idongme.app.go W/dalvikvm: VFY: unable to resolve new-instance 5185 (Lcom/idongme/greendaodemo/greendao/gen/DaoMaster$DevOpenHelper;) in Lcom/idongme/app/go/helper/SQLHelper;
11-18 16:50:48.472 24279-24279/com.idongme.app.go W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41616d58)
11-18 16:50:48.472 24279-24279/com.idongme.app.go E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.idongme.app.go, PID: 24279
                                                                    java.lang.NoClassDefFoundError: com.idongme.greendaodemo.greendao.gen.DaoMaster$DevOpenHelper
                                                                        at com.idongme.app.go.helper.SQLHelper.init(SQLHelper.java:26)
                                                                        at com.idongme.app.go.GoApplication.onCreate(GoApplication.java:142)
                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4388)
                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:138)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5061)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:812)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by greenrobot-team** [comment]
@smarterxiao Check [your ProGuard rules](http://greenrobot.org/greendao/documentation/technical-faq/) or disable multidex. Closing as this issue has seen no update in a long time. -ut

**Comment by bstonl** [comment]
1. [check proguard rules](http://greenrobot.org/greendao/documentation/technical-faq/)

2. if step1 is ok, check if has somethingelse about AOP such as plugin aspectj which may has exlcude rules
