### ISSUE TITLE
Error when compile DaoExample project

### ISSUE THREAD

**Issue by maxim-pandra** [greenrobot/greenDAO#378]
i downloaded ZIP archive. unpacked and imported it to Android Studio. then when Build DaoExample got this, please help =) 

:DaoExample:compileDebugJavaWithJavac
D:\AndroidStudioProjects\wellFormedSampleApps\greenDAO-master\greenDAO-master\DaoExample\build\generated\source\greendao\org\greenrobot\greendao\example\CustomerDao.java
Error:(16, 8) error: CustomerDao is not abstract and does not override abstract method hasKey(Customer) in AbstractDao
D:\AndroidStudioProjects\wellFormedSampleApps\greenDAO-master\greenDAO-master\DaoExample\build\generated\source\greendao\org\greenrobot\greendao\example\NoteDao.java
Error:(16, 8) error: NoteDao is not abstract and does not override abstract method hasKey(Note) in AbstractDao
D:\AndroidStudioProjects\wellFormedSampleApps\greenDAO-master\greenDAO-master\DaoExample\build\generated\source\greendao\org\greenrobot\greendao\example\OrderDao.java
Error:(21, 8) error: OrderDao is not abstract and does not override abstract method hasKey(Order) in AbstractDao
Note: D:\AndroidStudioProjects\wellFormedSampleApps\greenDAO-master\greenDAO-master\DaoExample\src\main\java\org\greenrobot\greendao\example\NoteActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Error:Execution failed for task ':DaoExample:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by SamoshkinR-Tem** [comment]
Same problem

**Comment by greenrobot** [comment]
Yes, we need to release a new version of the plugin to make it work again.

**Comment by slavomir-ziak** [comment]
is there a way to go around this problem?

**Comment by greenrobot-team** [comment]
You can temporarily remove the example project by commenting out `include 'DaoExample'` in `settings.gradle`. -ut

**Comment by ParitoshVaidya** [comment]
Getting same issue in version 3.1.1 

Code works fine with version 3.0.1

**Comment by greenrobot-team** [comment]
@ParitoshVaidya The [`3.1.1` examples](https://github.com/greenrobot/greenDAO/tree/V3.1.1/examples) work fine here. What error message do you get?
