### ISSUE TITLE
Dao is not abstract and does not override abstract method hasKey()

### ISSUE THREAD

**Issue by ParitoshVaidya** [greenrobot/greenDAO#432]
error: ClassNameDao is not abstract and does not override abstract method hasKey(ClassName) in AbstractDao

Getting this issue in version 3.1.1

Code works fine with version 3.0.1

**Comment by greenrobot-team** [comment]
If you are not using the Gradle plugin, yet, make sure to rebuild/generate your DAO classes. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by ParitoshVaidya** [comment]
I did not encounter this issue again after switching to 3.0.1

**Comment by RaymanMartin** [comment]
i think this problem may cause by different green dao version you use in gradle.

**Comment by AndroidFan1124** [comment]
The version in the project's gradle  of greendao plugin
 different from the version in  the module's gradle.
